version: '2'
services:
  igive2-app:
    image: igive2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://igive2-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=igive2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  igive2-mongodb:
    extends:
      file: mongodb.yml
      service: igive2-mongodb
