export const enum DataType {
  HEIGHT = 'HEIGHT',
  WEIGHT = 'WEIGHT',
  STEPS = 'STEPS',
  ACTIVETIME = 'ACTIVETIME',
  SEATEDTIME = 'SEATEDTIME',
  SYSTOLIC = 'SYSTOLIC',
  DYASTOLIC = 'DYASTOLIC',
  BREATHSPERMINUTE = 'BREATHSPERMINUTE',
  BREATHINGRAWDATA = 'BREATHINGRAWDATA',
  SLEEP = 'SLEEP'
}
