export const enum QuestionType {
  FREEANSWER = 'FREEANSWER',
  FREELONGANSWER = 'FREELONGANSWER',
  SINGLECHECKBOX = 'SINGLECHECKBOX',
  MULTIPLECHECKBOX = 'MULTIPLECHECKBOX',
  DATEANSWER = 'DATEANSWER',
  NUMERICANSWER = 'NUMERICANSWER'
}
